version: '3.9'

services:
  pwnamap:
    build: .  # Builds the Docker image from the current directory
    image: pwnamap:latest  # Name of the Docker image
    ports:
      - "1337:1337"  # Maps port 1337 on the host to port 1337 in the container
    volumes:
      - "${HOME}/.docker-data:/app/app/data"  # Volume mapping for persistent data
    restart: on-failure  # Restarts the container if it fails
    environment:
      APP_VERSION: "0.9.0"  # Application version
      LOG_LEVEL: "INFO"  # Logging level
      PYTHONUNBUFFERED: "1"  # Unbuffered Python output in the container
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:1337 || exit 1"]  # Health check command
      interval: 30s  # Runs every 30 seconds
      timeout: 10s  # Times out after 10 seconds
      retries: 3  # Retries three times before marking as unhealthy
