name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jakami/pwnamap:latest
    - name: Push the Docker image 
      run: docker login -u jakami -p ${{ secrets.DOCKER_TOKEN }} && docker push jakami/pwnamap:latest
